version: 1.0.{build}

environment:
  nodejs_version: "5.0"
  GithubEmail: johnny_reilly@hotmail.com
  GithubUsername: johnnyreilly
  GithubPersonalAccessToken:
    secure: T4M/N+e/baksVoeWoYKPWIpfahOsiSFw/+Zc81VuThZmWEqmrRtgEHUyin0vCWhl

install:
  - ps: Install-Product node $env:nodejs_version

branches:
  only:
    - master

# scripts to run before build
before_build:
- cmd: >-
    npm install

    npm install -g typings

    cd ./src

    typings install

    cd ../

build_script:
- cmd: >-
    npm run build

# before_test:
# - ps: >-
#     npm run test
# 
#     ../registerTestResults.ps1

deploy_script:
- ps: ./pushStatic.ps1 $env:APPVEYOR_BUILD_FOLDER $env:GithubEmail $env:GithubUsername $env:GithubPersonalAccessToken $env:APPVEYOR_REPO_NAME
